import type { AssetSpec } from '@/assets/spec';

/** Le concept artistique et le contrat du GLB sont volontairement deux étapes. */
export function promptsGemini(spec: AssetSpec) {
  const sujet = `ASSET : ${spec.id}\nDESCRIPTION ET VARIANTE : ${spec.description.fr}\nProportions largeur / hauteur / profondeur : ${spec.echelle.x.cible} / ${spec.echelle.y.cible} / ${spec.echelle.z.cible} mètres.`;
  const commun = `Miniature de stratégie en réalisme stylisé : matériaux crédibles, beaux volumes et silhouette lisible depuis une caméra à 65 degrés au-dessus de l’horizontale. Garder les reliefs architecturaux et mécaniques structurants, éviter le bruit de microdétails. Aucun texte, logo, symbole réel, drapeau national, personne, sang ou dégât de combat. Les interdictions priment sur tout accessoire contradictoire de la description. Les zones destinées à la couleur d’équipe sont gris neutre uni. Une seule identité géométrique, sans variantes mélangées.`;
  const concept = spec.type === 'terrain'
    ? `Crée une texture de sol vue strictement du dessus, sans perspective, pour ce terrain.\n${sujet}\n${commun}\nImage carrée, raccordable sur les quatre bords, albedo sans éclairage, ombre, relief de terrain ou objets détachés. Petits détails répartis sans motif dominant. Ne dessine pas de plaque 3D, cadre ou socle. Produis une seule image. Cette image est une référence de matière ; elle n’est pas un jeu complet de cartes PBR.`
    : `Crée UNE image de référence pour reconstruire ensuite cet objet dans Tripo.\n${sujet}\n${commun}\n${spec.type === 'kit' ? 'Utilise impérativement l’image jointe de la géométrie de base : change uniquement les matières et couleurs autorisées, jamais les volumes ou les pièces.' : ''}\nUn seul objet complet, vue trois-quarts avant légèrement plongeante, projection presque orthographique. Fond gris clair uniforme, éclairage de studio doux et neutre, sans ombre portée sur le fond. Aucun terrain, voisin, personnage, accessoire détaché, socle décoratif ou coupe intérieure. Marge autour de toutes les parties. Produis uniquement une image, pas une planche.`;
  const vues = `Joins l’image du concept approuvé. Représente EXACTEMENT cet objet : change seulement la caméra.\n${sujet}\n${commun}\nUne planche de six cases égales, trois colonnes et deux lignes. En haut : face, profil gauche, dos. En bas : profil droit, dessus, dessous. Aucun libellé dans l’image. Projection orthographique, même échelle physique par pixel, marges constantes. Conserve le nombre, la position et les proportions des ouvertures, roues, pièces, mât, toit et couleurs. Ne symétrise pas les côtés. Pour les surfaces cachées, reste simple et cohérent. Dessous fermé, sans coupe. Fond gris clair, lumière neutre sans ombre portée. Aucun ajout. Les images seront découpées avant utilisation ; cette planche ne doit pas être importée comme un seul objet dans Tripo.`;
  return { concept, vues };
}
