import { commandeAsset, nomModele, nomTexture, type AssetSpec } from '@/assets/index';
import { contratProduction } from '@/assets/production';
export function promptProduction(spec: AssetSpec, presents: readonly string[], source?: { revision: string } | null): string {
  const requis = [...spec.verification.lodRequis.map(l => nomModele(spec, l)), ...spec.textures.filter(t => t.obligatoire).map(t => nomTexture(spec, t.canal))];
  const manquants = requis.filter(n => !presents.includes(n));
  const contrat = contratProduction(spec);
  const sourceGlb = `SOURCE GLB PRIORITAIRE\nAvant toute modification, consulte GET /api/admin/assets/${spec.id}/sources avec la session administrateur ou le service de stockage configuré. Ne publie aucun jeton. ${source ? `Source sélectionnée : SHA-256 ${source.revision}. Télécharge GET /api/admin/assets/${spec.id}/sources?revision=${source.revision} et vérifie cette empreinte.` : 'Recherche la dernière source déposée ; fixe sa révision SHA-256 dans le compte rendu avant de travailler.'} Inspecte ce GLB et ses textures : c’est la source à préparer, même si un ancien lot existe dans le dépôt. Préserve son apparence ; ne le remplace jamais par une génération procédurale ou par un autre modèle. Si la source est inaccessible ou absente, demande le GLB au propriétaire et suspends sa préparation : aucun repli silencieux. Signale toute incompatibilité entre le détail de la source et les budgets avant une simplification qui changerait son apparence. Pour un kit, la géométrie et les UV de la base restent obligatoires ; signale une source incompatible. Indique la provenance et l’empreinte source dans la livraison.\n`;

  return `Produis et intègre l’asset ${spec.id} dans le dépôt Atlas Tournament.\nLis AGENTS.md, BRIEF.md, doc/11-assets-spec.md et assets/specs/${spec.id}.json avant de travailler. La spécification versionnée fait foi.\n${sourceGlb}\n${presents.length ? `Fichiers déjà présents : ${presents.join(', ')}. Ils servent de référence technique, jamais de remplacement du GLB source uploadé.` : 'Aucun fichier livré actuellement.'}\nFichiers obligatoires manquants : ${manquants.length ? manquants.join(', ') : 'aucun ; contrôler et améliorer le lot existant selon la demande'}.\n${contrat.reference ? `Référence : ${contrat.reference}. Lis sa fiche et les fichiers disponibles ; sa présence ne vaut pas approbation artistique.` : ''}\nLivre uniquement le modèle LOD0. Aucun LOD supplémentaire. Conserve les PNG externes sans copie embarquée. Aucun nouvel asset régional ou national hors de cette commande. Pour un kit, conserve exactement la géométrie, les UV, les nœuds et les animations de la base.\nPrépare le lot dans assets/livraisons/${spec.id}/ puis lance npm run controler:asset -- --spec assets/specs/${spec.id}.json --lot assets/livraisons/${spec.id}${spec.type === 'kit' && contrat.reference ? ' --base public/assets/modeles' : ''}. Corrige tous les refus avant intégration. Respecte les consignes du dépôt sur les contrôles visuels ; ne déclare jamais une approbation artistique automatique. Rends les fichiers, le verdict et le poids total.\n\nCONTRAT COMPLET\n${commandeAsset(spec)}`;
}
