#!/usr/bin/env python3
"""Rassemble les résultats réellement produits, sans lancer ni prétendre un contrôle absent."""
from pathlib import Path
from datetime import datetime, timezone
import argparse, hashlib, json
ID='decor_rocher_archipel';OUT=Path('tmp/production-sequentielle')/ID;SOURCE=Path('scripts/production/modeles')/ID
p=argparse.ArgumentParser();p.add_argument('--code-typecheck',required=True,type=int);args=p.parse_args();assert args.code_typecheck==0
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
read=lambda n:json.loads((OUT/n).read_text())
def save(name,data):(OUT/name).write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
now=datetime.now(timezone.utc).isoformat();fab=read('fabrication.json');measure=read('mesures.json');native=read('mesures-natif-glb.json');provenance=read('provenance.json');inspection=read('inspection-ancien-candidat.json')
old=Path('assets/livraisons')/ID/f'{ID}_lod0.glb';assert sha(old)==inspection['sha256Glb'];assert not (Path('public/assets/modeles')/f'{ID}_lod0.glb').exists()
assert fab['sha256Glb']==measure['sha256Glb']==native['sha256Glb']==sha(OUT/f'{ID}_lod0.glb')
text=(OUT/'validation-lot.log').read_text();verdict=json.loads(text[text.index('{'):]);assert verdict['ok'];save('validation-lot.json',verdict)
log=(OUT/'typecheck.log').read_text();assert 'tsc --noEmit --incremental false' in log and 'error TS' not in log
save('typecheck.json',{'date':now,'commande':'npm run typecheck -- --incremental false','codeSortie':args.code_typecheck,'journalSha256':sha(OUT/'typecheck.log'),'sourcesTypescript':[{'fichier':str(f),'sha256':sha(f)} for f in SOURCE.glob('*.ts')],'limite':'Typage seulement, pas de suite de tests ou build.'})
files=[{'fichier':f.name,'octets':f.stat().st_size,'sha256':sha(f)} for f in sorted(OUT.iterdir()) if f.suffix in ['.glb','.png']];assert len(files)==4
sources=[{'fichier':str(f),'sha256':sha(f)} for f in sorted(SOURCE.iterdir()) if f.suffix in ['.py','.ts','.md']]
save('source.json',{'id':ID,'nature':'creation_originale_parametrique','date':now,'verificationDistante':provenance['lectureDistanteCommuniquee'],'maitreLocalIdentifie':False,'scripts':sources,'ancienCandidat':inspection['sha256Glb'],'geometriePrecedenteReutilisee':False,'texturesPrecedentesReutilisees':False,'decimation':False,'bakeHD':False,'approbationArtistique':False})
report={'id':ID,'date':now,'etat':'controle_technique_reussi','source':'creation_originale_parametrique','verificationDistante':provenance['lectureDistanteCommuniquee'],'maitreLocalIdentifie':False,'ancienCandidat':{'sha256':inspection['sha256Glb'],'triangles':inspection['triangles'],'octetsGlb':inspection['octetsGlb'],'preserve':True,'actifAbsent':True,'geometrieReutilisee':False},'triangles':fab['triangles'],'budgetTriangles':900,'primitives':1,'materiaux':1,'octetsGlb':fab['octetsGlb'],'octetsLot':sum(f['octets'] for f in files),'dimensions':fab['bornes']['dimensions'],'sha256Glb':fab['sha256Glb'],'fichiers':files,'sources':sources,'controleLot':verdict,'typecheck':'typecheck.json','mesures':{'rapport':'mesures.json','natif':'mesures-natif-glb.json','volumesFermes':5,'plansDeFracture':14,'alveolesGeometriques':5,'appuisCoquillages':4,'gardeCoquillagesBlocMinM':min(x['gardeBlocM'] for x in measure['appuisCoquillages']),'pariteNumpyNatif':True,'ecartBornesNatifMaxM':native['ecartBornesMaxM'],'controleExhaustifCollisions':False},'textures':'textures.json','provenance':'provenance.json','inspection':'inspection-ancien-candidat.json','pertes':{'decimation':False,'reductionTexture':False,'bakeHD':False,'ancienModeleRemplaceParCreationIndependante':True},'approbationArtistique':False,'controleVisuel':False,'testsGeneraux':False,'build':False,'fpsTelephone':None,'limites':['Profils numériquement différents ; lisibilité et esthétique non jugées.','Coutures UV artistiquement non inspectées ; dessous des coquilles partage son îlot supérieur.','Aucune variante saisonnière dédiée, cartes communes.','Raccordement runtime et instanciation contrôlés séparément par le coordinateur.','Aucun rendu, capture, contrôle visuel, test général, build ni FPS téléphone.']}
save('revue-technique.json',report);print(json.dumps({'id':ID,'triangles':report['triangles'],'octetsLot':report['octetsLot'],'sha256Glb':report['sha256Glb'],'controle':'ok','typecheck':'ok'}))
